### PR TITLE
[DPE-5015] Fix integration hub not parsing equals sign properly

### PR DESCRIPTION
**Pull request by theoctober19th**

### CODE REVIEW

**Review by deusebio — COMMENTED** [review]
Could we maybe have a small tests with the use case of the double equals?

**Comment by deusebio** [comment]
Oki! Just realized that we don't have tests here. Let's then skip the tests here, but it would be good to have that tests in the integration hub. 

It should be pretty easy, we set the charm to populate a config with double equals, and we make sure that we can fetch that

**Review by deusebio — APPROVED** [review]

**Comment by theoctober19th** [comment]
@deusebio I have those tests in the Operator. Since there are no tests here, adding them from scratch felt more like a separate task with wider scope.

Here is the PR: https://github.com/canonical/spark-integration-hub-k8s-operator/pull/18

**Comment by deusebio** [comment]
@deusebio yes yes, I noticed and I have revised my comment above and approved. 

We are on the same page, as you have already implemented the tests in the operator! Thanks!

**Pull request merged**
